### ISSUE TITLE
Something wrong with the date

### ISSUE THREAD

**Issue by wayson** [coderzh/hugo-pacman-theme#12]
I have applied the theme to my website. But it will show WARNING message when I run "hugo server" as follows:

![capture](https://cloud.githubusercontent.com/assets/3485960/24335978/31c269ce-12d3-11e7-97e4-46bc0fd6b647.PNG)

What's more, the dates of the post are wrong:

![capture_2](https://cloud.githubusercontent.com/assets/3485960/24335995/71837f4e-12d3-11e7-9e01-ab822b7cee8f.PNG)

![capture_3](https://cloud.githubusercontent.com/assets/3485960/24335996/75534320-12d3-11e7-8297-2cdca4a51bf3.PNG)

The setting is as follows:
![capture_4](https://cloud.githubusercontent.com/assets/3485960/24335999/8f87af4c-12d3-11e7-8f38-8b243ba1a9bc.PNG)

Any solution for this?

Thank you.

**Comment by coderzh** [comment]
@wayson 
The DateFormat and MonthFormat used in the config is the specific time:

Mon Jan 2 15:04:05 MST 2006

So, you must change it to DateFormat = "2006-01-02" and MonthFormat = "2006-01"

(See golang time doc: https://golang.org/pkg/time/)
