### ISSUE TITLE
hugo0.27的兼容性问题

### ISSUE THREAD

**Issue by peach5460** [coderzh/hugo-pacman-theme#17]
使用hugo的0.27版本生成时，报有警告
WARNING: Site config's rssURI is deprecated and will be removed in a future release. Set baseName in outputFormats.RSS.
ERROR Page's Now is deprecated and will be removed in Hugo 0.27. Use now (the template func).

![image](https://user-images.githubusercontent.com/3350332/30363131-a5eacd34-9891-11e7-9e13-ce4282144c73.png)

**Comment by coderzh** [comment]
@peach5460 done.
