### ISSUE TITLE
Fix theme.toml

### ISSUE THREAD

**Issue by kaushalmodi** [coderzh/hugo-pacman-theme#18]
- Can you please provide 2 or 3 **tags** in the `theme.toml` that describe your theme very well?
- Also the `homepage` in the `theme.toml` is pointing to your blog. That front-matter is used on https://themes.gohugo.io/hugo-pacman-theme/ to create the Home button. So it will be useful to users if that front-matter were set to this theme's repo link: https://github.com/coderzh/hugo-pacman-theme

Thanks!

**Comment by coderzh** [comment]
@kaushalmodi done.
