### ISSUE TITLE
Comment area failed to load

### ISSUE THREAD

**Issue by Bivectorfoil** [coderzh/hugo-pacman-theme#20]
I noticed that in line 35 of file **hugo-pacman-theme/layouts/partials/comment.html,** in the middle of the **.DisqusShortName** variable , a dot **" . "** is missing. The dot should be between **.Disqus** and **ShortName**. Like this:
`s.src = '//{{ .Site.Params.Disqus.ShortName }}.disqus.com/embed.js;`

Otherwise it will not be able to load the Disqus js file and causes the comment area failed to load.

Anyway, Truly thanks for the Theme!

**Comment by coderzh** [comment]
Fixed,  many thanks.
