### ISSUE TITLE
点more的时候,链接地址在哪里?

### ISSUE THREAD

**Issue by peach5460** [coderzh/hugo-pacman-theme#7]
请问一下,列表底下点more以后...进入了 baseurl/post/ 这个地址
但是我的文档没有建post文件夹,我也不太想把所有的文章都放在post下...
请问应该如何更改

**Comment by coderzh** [comment]
https://github.com/coderzh/hugo-pacman-theme/blob/master/layouts/index.html

改这个文件

**Comment by peach5460** [comment]
3Q
